#!/bin/sh

loc=$PWD
[ -n "$1" ] && loc=$1

mkdir $loc/portrait
mkdir $loc/landscape

for file in $loc/*.jpg $loc/*.png $loc/*.gif
do
  r=$(identify -format '%[fx:(h>w)]' "$file")
  if [[ r -eq 1 ]] 
  then
  echo "Moving $file to portrait folder..."
  mv "$file" $loc/portrait/
  else
  echo "Moving $file to landscape folder..."
  mv "$file" $loc/landscape/
  fi
done
